<a href="https://colab.research.google.com/github/stavesqukk/0011/blob/master/LAB_7_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a[0]

np.int64(1)

In [5]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [6]:
a[:3]

array([10,  2,  3])

In [7]:
b = a[3:]
b


array([4, 5, 6])

In [8]:
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [9]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
a[1, 3]

np.int64(8)

In [11]:
a.ndim

2

In [13]:
a.shape

(3, 4)

In [14]:
len(a.shape) == a.ndim

True

In [15]:
a.size

12

In [16]:
import math
a.size == math.prod(a.shape)

True

In [17]:
a.dtype

dtype('int64')

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [21]:
np.arange(4)

array([0, 1, 2, 3])

In [22]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [23]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [24]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [26]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [27]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [29]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [31]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [33]:
array_example.ndim

3

In [34]:
array_example.size

24

In [35]:
array_example.shape

(3, 2, 4)

In [36]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [37]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [40]:
import numpy as np

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
np.reshape(a, (1, 6))

array([[1, 2, 3, 4, 5, 6]])

In [43]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [44]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [45]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [46]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [47]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [48]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [49]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [51]:
data = np.array([1, 2, 3])

data[1]

np.int64(2)

In [52]:
data[0:2]

array([1, 2])

In [53]:
data[1:]

array([2, 3])

In [54]:
data[-2:]

array([2, 3])

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [56]:
print(a[a < 5])

[1 2 3 4]


In [57]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [58]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [59]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [60]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [61]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [62]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [63]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [64]:
print(a[b])

[1 2 3 4]


In [65]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [66]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [68]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [69]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [70]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [71]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [72]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [73]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [74]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [75]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [76]:
b1[0] = 99

In [77]:
b1

array([99,  2,  3,  4])

In [78]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [79]:
b2 = a.copy()

In [80]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [81]:
data - ones

array([0, 1])

In [82]:
data * data

array([1, 4])

In [83]:
data / data

array([1., 1.])

In [84]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [85]:
b = np.array([[1, 1], [2, 2]])

In [86]:
b.sum(axis=0)

array([3, 3])

In [87]:
b.sum(axis=1)

array([2, 4])

In [88]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [89]:
data = np.array([1, 2, 3])

In [90]:
data.max()

np.int64(3)

In [91]:
data.min()

np.int64(1)

In [92]:
data.sum()

np.int64(6)

In [93]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [94]:
a.sum()

np.float64(4.8595784)

In [95]:
a.min()

np.float64(0.05093587)

In [96]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [97]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
data[0, 1]

np.int64(2)

In [99]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [100]:
data[0:2, 0]

array([1, 3])

In [101]:
data.max()

np.int64(6)

In [102]:
data.min()

np.int64(1)

In [103]:
data.sum()

np.int64(21)

In [104]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [105]:
data.max(axis=0)

array([5, 6])

In [106]:
data.max(axis=1)

array([2, 5, 6])

In [107]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [108]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [109]:
np.ones((4, 3, 2))




array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [110]:
np.ones(3)

array([1., 1., 1.])

In [111]:
np.zeros(3)

array([0., 0., 0.])

In [112]:
rng = np.random.default_rng()  # the simplest way to generate random numbers


In [113]:
rng.random(3)

array([0.10412041, 0.40955369, 0.22356597])

In [114]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [115]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [116]:
rng.random((3, 2))

array([[0.95113747, 0.75540211],
       [0.03729839, 0.36095516],
       [0.04076617, 0.06822013]])

In [117]:
rng.integers(5, size=(2, 4))

array([[0, 2, 2, 4],
       [0, 3, 1, 4]])

In [118]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [119]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [120]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [121]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [122]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [123]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [124]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [125]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [126]:
print(indices)

[0 1 2]


In [127]:
print(occurrence_count)

[2 1 1]


In [128]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [130]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [131]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [132]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [133]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
reversed_arr = np.flip(arr)

In [135]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [136]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [137]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [138]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [139]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [140]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [141]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


In [142]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [143]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [144]:
a1 = x.flatten()

In [145]:
a1[0] = 99


In [146]:
print(x)  # Original array


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [147]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [148]:
a2 = x.ravel()

In [149]:
a2[0] = 98


In [150]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [151]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]


In [152]:
help(max)



Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value

    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [153]:
a = np.array([1, 2, 3, 4, 5, 6])

In [154]:
def double(a):
  '''Return a * 2'''
  return a * 2


In [155]:
a = np.array([1, 2, 3, 4, 5, 6])

In [156]:
np.save('filename', a)

In [157]:
b = np.load('filename.npy')

In [158]:
print(b)

[1 2 3 4 5 6]


In [159]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [160]:
np.savetxt('new_file.csv', csv_arr)

In [161]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])